RaiteRaju.Web/Controllers/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RaiteRaju.ServiceMapper;
using RaiteRaju.Web.Models;
using System.IO;
using System.Text.RegularExpressions;

namespace RaiteRaju.Web.Controllers
{
    public class FooterController : ErrorController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult Careers()
        {
            return View();
        }

        public ActionResult ContactUs()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ContactUs(FormCollection ContUs)
        {
            ContactUsModel ModelObj = new ContactUsModel();
            int success = 0;

            ModelObj.PhoneNumber = Convert.ToInt64(ContUs["txtPhoneNumber"]);
            ModelObj.Subject = ContUs["txtSubject"];
            ModelObj.Description = ContUs["txtContactUsDescription"];
            int count = 0;
            if (System.Text.RegularExpressions.Regex.Match(ModelObj.PhoneNumber.ToString(), @"^[56789]\d{9}$").Success)
            {
                count = count + 1;
            }
            string s = "[^<>'\"/`%-]";
            if (System.Text.RegularExpressions.Regex.IsMatch(ModelObj.Subject, s))
            {
                count = count + 1;
            }
            if (System.Text.RegularExpressions.Regex.IsMatch(ModelObj.Description, s))
            {
                count = count + 1;
            }
            ManagementServiceWrapper manobj = new ManagementServiceWrapper();
            if (count == 3)
            {
                success = manobj.insertContactUs(ModelObj);
            }
           return Json(success,JsonRequestBehavior.AllowGet) ;
        }

        public ActionResult ReportIssue()
        {
            return View();
        }
        
        public ActionResult Help()
        {
            return View();
        }

        public ActionResult Reviews()
        {
            List<GDictionaryModel> list = new List<GDictionaryModel>();
            InformationServiceWrapper InforObj = new InformationServiceWrapper();
            list = InforObj.FetchReviews();
            ViewBag.ReviewList = list;
            return View();
        }

        [HttpPost]
        public ActionResult Reviews(FormCollection RVCollection)
        {
            int success = 0;
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];

            if (UserIdCookie.Value != null)
            {
                Utility en = new Utility();
                    string ReviewDescription = RVCollection["txtReviewDescription"];
                    Int64 PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                    ManagementServiceWrapper wrapobj = new ManagementServiceWrapper();
                    success = wrapobj.InsertReview(PhoneNumber, ReviewDescription);
                }
                else
                {
                    success = 0;
                }
            return Json(success,JsonRequestBehavior.AllowGet);
                
        }

        public ActionResult TermsAndConditions()
        {
            return View();
        }

        public ActionResult TermsOfUse()
        {
            return View();
        }

        public ActionResult FeaturedAds()
        {
            return View();
        }

        public ActionResult HowToRegister()
        {
            return View();

        }

        public ActionResult HowToBook()
        {
            return View();
        }

        public ActionResult Partner()
        {
            return View();
        }

        public ActionResult Promotions()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Promotions(FormCollection Promote)
        {
            ContactUsModel ModelObj = new ContactUsModel();
            int success = 0;

            Int64 PhoneNumber = Convert.ToInt64(Promote["txtPhoneNumber"]);
            string Name = Promote["txtName"];
            string Description = Promote["txtContactUsDescription"];
            int count = 0;

            if (System.Text.RegularExpressions.Regex.Match(PhoneNumber.ToString(), @"^[56789]\d{9}$").Success)
            {
                count = count + 1;
            }
            string s = "[^<>'\"/`%-]";
            if (System.Text.RegularExpressions.Regex.IsMatch(Name, s))
            {
                count = count + 1;
            }
            if (System.Text.RegularExpressions.Regex.IsMatch(Description, s))
            {
                count = count + 1;
            }
            ManagementServiceWrapper manobj = new ManagementServiceWrapper();
            if (count == 3)
            {
                success = manobj.InsertPromotions(Name, PhoneNumber, Description);
            }
            return Json(success, JsonRequestBehavior.AllowGet);
        }
    }
}

RaiteRaju.Web/Controllers/PartnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RaiteRaju.ServiceMapper;
using RaiteRaju.Web.Models;
using System.Web.UI.WebControls;
using System.Text.RegularExpressions;
using RaiteRaju.ApplicationUtility;

namespace RaiteRaju.Web.Controllers
{
    public class PartnerController : ErrorController
    {
        // GET: Partner

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OwnerRegistration()
        {
                return View();
        }

        [HttpPost]
        public ActionResult OwnerRegistration(FormCollection form)
        {
            Owner model = new Owner();
            Utility en = new Utility();

            Random r = new Random();
            Int32 OTP = r.Next(100000, 999999);

            Int32 ownerID = 0;

            model.txtOwnerName = form["txtUserName"];
            model.BigIntPhoneNumber = Convert.ToInt64(form["txtPhoneNumber"]);
            model.txtPassword = en.Encrypt(form["txtPassword"]);
            model.intStateId = Convert.ToInt32(form["ddlStateID"]);
            model.intDistrictId = Convert.ToInt32(form["ddlDistrictID"]);
            model.intManadalID = Convert.ToInt32(form["ddlMandalID"]);
            model.txtPlace = form["txtVillage"];
            model.OTP = OTP;

            string errorMessage = "";

            string s = "[^<>'\"/`%-]";
            if (!System.Text.RegularExpressions.Regex.IsMatch(model.txtOwnerName, s))
            {
                errorMessage = errorMessage + "Special character are not allowed in Name.\n";
            }

            if (!System.Text.RegularExpressions.Regex.IsMatch(en.Decrypt(model.txtPassword), s))
            {
                errorMessage = errorMessage + "Special character are not allowed in password.\n";
            }

            if (!System.Text.RegularExpressions.Regex.Match(model.BigIntPhoneNumber.ToString(), @"^[56789]\d{9}$").Success)
            {
                errorMessage = errorMessage + "Enter valid Phone Number.\n";
            }

            if (!Regex.Match(model.intStateId.ToString(), "[1-9]").Success)
            {
                errorMessage = errorMessage + "Select valid State.\n";
            }

            if (!Regex.Match(model.intDistrictId.ToString(), "[1-9]").Success)
            {
                errorMessage = errorMessage + "Select valid District.\n";
            }

            if (!Regex.Match(model.intManadalID.ToString(), "[1-9]").Success)
            {
                errorMessage = errorMessage + "Select valid Mandal.\n";
            }


            if (!System.Text.RegularExpressions.Regex.IsMatch(model.txtPlace, s))
            {
                errorMessage = errorMessage + "special characters are not allowed in Place.\n";
            }


            GDictionaryModel GDOBJ = new GDictionaryModel();
            if (errorMessage == "")
            {
                ManagementServiceWrapper ObjService = new ManagementServiceWrapper();
                InformationServiceWrapper infoObj = new InformationServiceWrapper();
                GDOBJ = infoObj.MobileNuberExistsOrNot(model.BigIntPhoneNumber, UserType.owner.ToString());
                if (GDOBJ.ID == 1)
                {
                    ManagementServiceWrapper serviceObj = new ManagementServiceWrapper();


                    ownerID = serviceObj.VehicleOwnerRegistration(model);

                    if (ownerID != 0)
                    {
                        HttpCookie KeyCookie = new HttpCookie("_RRPS");
                        KeyCookie.Values["_RRPS"] = en.Encrypt(model.txtPassword);
                        KeyCookie.Expires = DateTime.Now.AddDays(365);
                        Response.Cookies.Add(KeyCookie);
                    }
                    return Json("success", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    errorMessage = "Entered mobiler number is already registered with us.\n";
                    return Json(errorMessage, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(errorMessage, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult _VehicleList(int PageNumber)
        {
            int TotalPageNumber = 0;
            ViewBag.CurrentPageNumber = PageNumber;
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();

            if (UserNameCookie != null && KeyCookie != null)
            {
                Int64 PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                string PassWord = en.Decrypt(KeyCookie["_RRPS"].ToString());
                List<Vehicle> ListObj = new List<Vehicle>();
                InformationServiceWrapper Obj = new InformationServiceWrapper();
                ListObj = Obj.GetVehicleDetails(PhoneNumber, PassWord, PageNumber, out TotalPageNumber);
                if (ListObj != null)
                {
                    ViewBag.vehicleList = ListObj;
                }
            }
            else if (UserNameCookie != null && OTPCookie != null)
            {
                Int64 PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                Utility UtilObj = new Utility();
                string OTP = UtilObj.Decrypt(OTPCookie["_ROTP_"]);
                List<Vehicle> ListObj = new List<Vehicle>();
                InformationServiceWrapper Obj = new InformationServiceWrapper();
                ListObj = Obj.GetVehicleDetails(PhoneNumber, OTP, PageNumber, out TotalPageNumber);
                if (ListObj != null)
                {
                    ViewBag.vehicleList = ListObj;
                }
            }
            ViewBag.TotalPageNumber = TotalPageNumber;
            return PartialView("_VehicleList");
        }

        public ActionResult AddVehicle()
        {

            return View();
        }

        [HttpPost]
        public ActionResult AddVehicle(FormCollection form)
        {
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();
            string returnvalue = "";
            if ((PhoneNumberCookie != null && KeyCookie != null) || (PhoneNumberCookie != null && OTPCookie != null))
            {
                Vehicle model = new Vehicle();
                model.BigIntPhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                model.intVehicleTypeID = Convert.ToInt32(form["ddlVehicleTypeID"]);
                model.txtVehicleName = form["txtVehicleModel"];
                model.txtVehicleNumber = form["txtVehicleNumber"].ToUpper();

                ManagementServiceWrapper mangeObj = new ManagementServiceWrapper();
                returnvalue=mangeObj.AddVehicle(model);
                return Json(returnvalue, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(returnvalue, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult DeleteVehicle(int VehicleID)
        {
            int succuss = 0;
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();
            if (PhoneNumberCookie != null)
            {

                ManagementServiceWrapper obj = new ManagementServiceWrapper();
                Int64 BigIntPhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                obj.DeleteVehicle(VehicleID, BigIntPhoneNumber);
                return Json(1, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Json(succuss, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EditVehicleDetails(int VehicleID)
        {
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();

            if ((PhoneNumberCookie != null && KeyCookie != null) || (PhoneNumberCookie != null && OTPCookie != null))
            {
                InformationServiceWrapper obj = new InformationServiceWrapper();
                Vehicle model = new Vehicle();
                Int64 PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                model = obj.GetVehicledDetailsByID(VehicleID, PhoneNumber);
                ViewBag.VehicleTypeID = model.intVehicleTypeID;
                ViewBag.VehicleName = model.txtVehicleName;
                ViewBag.VehicleNumber = model.txtVehicleNumber;
                ViewBag.VehicleId = model.intVehicleID;

                    
            }
            return View();
        }

        [HttpPost]
        public ActionResult UpdateVehicleDetails(FormCollection form)
        {
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];

RaiteRaju.Web/Views/Footer/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
    Layout = "~/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $.noConflict();
    jQuery().ready(function () {
        jQuery('#tabAboutUs').addClass('active');
    });
</script>

<div class="container">
    <div  class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <h3 class="FormHeading text-left">About Us</h3>
            <p class="font14">
                Our motive is to provide vehicles to the needy who wants to travel outstations or delivery goods to some place.
                We have network of vehicles which are ready be hired by needy and also have very trained driver who can help you in dropping you at your destination safely.
            </p>
            <br />
            <h5 style="padding-left:35px;padding-bottom:10px;">Currently Serving vehicles are</h5>
            <ul style="padding-left:50px;" class="font14">
                <li>Mini Truck</li>
                <li>Auto</li>
                <li>Cars</li>
                <li>Mini Bus</li>
                <li>Bus</li>
                <li>Lorry</li>
                <li>Mini Auto</li>
            </ul>
            <br>
            <br>
            <h5 style="padding-left:35px;padding-bottom:10px;">BellaCabs.in Offering services are</h5>
            <ul style="padding-left:50px;" class="font14">
                <li>we provide Cars(4 Seater, 7 Seater and 14 Seater), Mini buses and Buses for travelling outstation or Tours</li>
                <li>Trucks, Mini Trucks and Lorries can be provided for delivering goods</li>
                <li>we can arrange drivers for you vehicles</li>
                <li>we</li>
                <li>Bus</li>
                <li>Lorry</li>
                <li>Mini Auto</li>
            </ul>
        </div>
</div>
    <div class="row py-5">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <h2 class="FormHeading py-2" style="text-align:left">Your can reach us at</h2>
            <ul class="pl-4" style="font-size:14px;font-family:inherit">
                <li class="py-2">Customer Care<br />EmailID: support@bellacabs.in<br />Phone No: 8310276613</li>
            </ul>
        </div>
    </div>
</div>

RaiteRaju.Web/Views/Footer/Careers.cshtml
@{
    ViewBag.Title = "Careers";
    Layout = "~/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $.noConflict();
    jQuery().ready(function () {
        jQuery('#tabCareers').addClass('active');
    });
</script>

<div class="container" style="min-height:600px;">
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <h2 style="align-content:center;padding-top:50px" class="FormHeading text-left">Careers</h2>
            <p class="font14">Thanks for showing interest in us. Please send your Resume to below mentioned mailId.<br /> Our Team will get in touch with you. careers@bellacabs.in</p>
            </div>
        </div>
    </div>
            

RaiteRaju.Web/Views/Footer/ContactUs.cshtml
@{
    ViewBag.Title = "ContactUs";
    Layout = "~/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $.noConflict();
    jQuery(document).ready(function () {
        jQuery("#Message").html("");
        jQuery('#tabContactUs').addClass('active');
    });

    function fnValidation() {
        var message = "";
        var phone = jQuery("#txtPhoneNumber").val(), intRegex = /^[5-9]{1}[0-9]{9}$/;

        if (jQuery("#txtPhoneNumber").val() == "") {
            message = message + "Please Enter Phone Number.<br />";
        }
        else if (phone != "" && intRegex.test(phone) == false) {
            message = message + "Please Enter Valid Phone Number.<br />";
        }

        if (jQuery("#txtSubject").val() == "") {
            message = message + "Please Enter Subject.<br />";
        }
        else if (jQuery("#txtSubject").val() != "" && /^[^<>'\"/`%-]*$/.test(jQuery("#txtSubject").val()) == false) {
            message = message + "Special Characters Are Not Allowed In Subject.<br />";
        }
        else if (jQuery("#txtSubject").val().length > 50 || jQuery("#txtSubject").val().length < 4) {
            message = message + "Subject Should Be Between 4 To 50 Characters.<br />";
        }

        if (jQuery("#txtContactUsDescription").val() == "") {
            message = message + "Please Enter Description.<br />";
        }
        else if (jQuery("#txtContactUsDescription").val() != "" && /^[^<>'\"/`%-]*$/.test(jQuery("#txtContactUsDescription").val()) == false) {
            message = message + "Special Characters Are Not Allowed In Description.<br /> ";
        }
        else if (jQuery("#txtContactUsDescription").val().length > 200 || jQuery("#txtContactUsDescription").val().length < 4) {
            message = message + "Description Should Be Between 4 To 200 Characters.<br />";
        }
        if (message == "") {
            return true;
        }
        else {
            jQuery("#Message").html(message).css("color", "Red");
            return false;
        }
    }

    function fnContactUs() {

        var form = jQuery("#ContactUsForm").serialize();

        if (fnValidation()) {
            jQuery.ajax({
                type: 'POST',
                url: '@Url.Action("ContactUs", "Footer")',
                dataType: 'json',
                data: form,
                success: function (result) {
                    if (result == 1) {
                        jQuery("#Message").html("Submitted Successfully, Our Team Will Get In Touch With You.").css("color", "green");
                        jQuery("#ContactUsForm")[0].reset();
                    }
                    else if (result == 0) {
                        jQuery("#Message").html("Please Enter Data as per validation").css("color", "Red");
                    }
                    else {
                        alert("Some Error Occured. Please Try After Sometime.");
                        window.location.href = '@Url.Action("Home", "Home")';
                    }
                },
                error: function (err) {
                    jQuery("#Message").html("Some Error Occured. Please Try After Sometime.");
                }
            });
        }
    }
</script>
<div id="divContactUs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

    @using (Html.BeginForm("ContactUs", "Footer", FormMethod.Post, new { id = "ContactUsForm" }))
                {

        <h3 class="FormHeading">Write here to reach us</h3>
                    <div class="form-box clearfix">
                    <h3 class="form-heading text-center">Write Now</h3>
                        <div id="Message" style="padding-left:20px">
                        </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="txtPhoneNumber">Mobile<span class="MandatoryStars">*</span> :</label>
                                <input type="text" class="form-control" id="txtPhoneNumber" name="txtPhoneNumber" placeholder="9999999999" maxlength="10">
                            </div>
                        </div>
                        <div class="col-md-11">
                            <div class="form-group">
                                <label for="txtSubject">Subject<span class="MandatoryStars">*</span>:</label>
                                @Html.TextBox("txtSubject", null, new { @class = "form-control", @placeholder = " Enter Subject" })
                            </div>
                        </div>
                        <div class="col-md-11">
                            <div class="form-group">
                                <label for="">Description<span class="MandatoryStars">*</span>:</label>
                                @Html.TextArea("txtContactUsDescription", null, new { @class = "form-control", @placeholder = " Enter Descriptioin"})
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-12 text-center">
                            <div class="cta-actions">
                                <input id="btnRegister" type="button" value="Submit Details" class="ghost-btn first last filled" onclick="fnContactUs()" />
                            </div>
                        </div>
                    </div>
                </div>
    }

            </div>
        </div>
        <div class="row py-5">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <h2 class="FormHeading py-2" style="text-align:left">Your can also reach us at</h2>
                <ul class="pl-4 font14" >
                    <li class="py-2">Customer Care:-<br />EmailID:  support@bellacabs.in <br />Phone Number:  8310276613
                    
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

RaiteRaju.Web/Views/Footer/FeaturedAds.cshtml
@{
    ViewBag.Title = "FeaturedAds";
    Layout = "~/Shared/_Layout.cshtml";
}

<h2>FeaturedAds</h2>

RaiteRaju.Web/Views/Footer/Help.cshtml
@{
    ViewBag.Title = "Help";
    Layout = "~/Shared/_Layout.cshtml";
}

<h2>Help</h2>
<div>
    <table>
        <tr>
            <td style="font-family:Verdana,sans-serif;font-size:18px"><a href="#">How to avail this website?</a></td>

        </tr>
        <tr>
            <td style="font-family:Verdana,sans-serif;font-size:18px"><a href="#">How to Register?</a></td>
        </tr>
        <tr>
            <td style="font-family:Verdana,sans-serif;font-size:18px"><a href="#">How to Book Vehicle?</a></td>
        </tr>
        <tr>
            <td style="font-family:Verdana,sans-serif;font-size:18px"><a href="#">How to attach your vehicle?</a></td>
        </tr>
        <tr>
            <td style="font-family:Verdana,sans-serif;font-size:18px"><a href="#">How to Manage your Vehicle list</a></td>
        </tr>
          
    </table>
</div>

RaiteRaju.Web/Views/Footer/Promotions.cshtml
@{
    ViewBag.Title = "Promotions";
    Layout = "~/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $.noConflict();
    jQuery(document).ready(function () {
        jQuery("#Message").html("");
        jQuery('#tabPromotions').addClass('active');
    });

    function fnValidation() {
        var message = "";
        var phone = jQuery("#txtPhoneNumber").val(), intRegex = /^[5-9]{1}[0-9]{9}$/;

        if (jQuery("#txtName").val() == "") {
            message = message + "Please Enter Name.<br />";
        }
        else if (jQuery("#txtName").val() != "" && /^[^<>'\"/`%-]*$/.test(jQuery("#txtName").val()) == false) {
            message = message + "Special Characters Are Not Allowed In Name.<br />";
        }
        else if (jQuery("#txtName").val().length > 50 || jQuery("#txtName").val().length < 4) {
            message = message + "Name Should Be Between 4 To 50 Characters.<br />";
        }
        if (jQuery("#txtPhoneNumber").val() == "") {
            message = message + "Please Enter Phone Number.<br />";
        }
        else if (phone != "" && intRegex.test(phone) == false) {
            message = message + "Please Enter Valid Phone Number.<br />";
        }


        if (jQuery("#txtContactUsDescription").val() == "") {
            message = message + "Please Enter Description.<br />";
        }
        else if (jQuery("#txtContactUsDescription").val() != "" && /^[^<>'\"/`%-]*$/.test(jQuery("#txtContactUsDescription").val()) == false) {
            message = message + "Special Characters Are Not Allowed In Description.<br /> ";
        }
        else if (jQuery("#txtContactUsDescription").val().length > 200 || jQuery("#txtContactUsDescription").val().length < 4) {
            message = message + "Description Should Be Between 4 To 200 Characters.<br />";
        }
        if (message == "") {
            return true;
        }
        else {
            jQuery("#Message").html(message).css("color", "Red");
            return false;
        }
    }

    function fnContactUs() {

        var form = jQuery("#PromotionsForm").serialize();

        if (fnValidation())
            jQuery.ajax({
                type: 'POST',
                url: '@Url.Action("Promotions", "Footer")',
                dataType: 'json',
                data: form,
                success: function (result) {
                    if (result == 1) {
                        jQuery("#Message").html("Thanks for your interest in us, We will get back to you ASAP.").css("color", "green");
                        jQuery("#PromotionsForm")[0].reset();
                    }
                    else if (result == 0) {
                        jQuery("#Message").html("Please Enter Data as per validation").css("color", "Red");
                    }
                    else {
                        alert("Some Error Occured. Please Try After Sometime.");
                        window.location.href = '@Url.Action("Home", "Home")';
                    }
                },
                error: function (err) {
                    jQuery("#Message").html("Some Error Occured. Please Try After Sometime.");
                }
            });
    }
</script>

<div id="divContactUs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("Promotions", "Footer", FormMethod.Post, new { id = "PromotionsForm" }))
                {
                    <h3 class="FormHeading">Write here to promote your business with us</h3>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <p style="font-size:16px;font-family:inherit;">You can promote your business here with us, so that you can reach maximum users related automobile and tranportation through our website. We are very happy to help you in promoting your business on our website.</p>
        </div>
    </div>
        <div class="form-box clearfix">
            <h3 class="form-heading text-center">Write Now</h3>
            <div id="Message" style="padding-left:20px">
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label>Name<span class="MandatoryStars">*</span>:</label>
                        @Html.TextBox("txtName", null, new { @class = "form-control", @placeholder = " Name" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="txtPhoneNumber">Mobile<span class="MandatoryStars">*</span> :</label>
                        <input type="text" class="form-control" id="txtPhoneNumber" name="txtPhoneNumber" placeholder="9999999999" maxlength="10">
                    </div>
                </div>
                <div class="col-md-11">
                    <div class="form-group">
                        <label for="">Description<span class="MandatoryStars">*</span>:</label>
                        @Html.TextArea("txtContactUsDescription", null, new { @class = "form-control", @placeholder = " Enter Descriptioin" })
                    </div>
                </div>
                <div class="col-md-12 col-sm-12 text-center">
                    <div class="cta-actions">
                        <input id="btnRegister" type="button" value="Submit Details" class="ghost-btn first last filled" onclick="fnContactUs()" />
                    </div>
                </div>
            </div>
        </div>}

    </div>
        </div>
    </div>
</div>

RaiteRaju.Web/Views/Footer/TermsOfUse.cshtml
@{
    ViewBag.Title = "TermsOfUse";
    Layout = "~/Shared/_Layout.cshtml";
}

<h2>TermsOfUse</h2>