RaiteRaju.Web/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RaiteRaju.ServiceMapper;
using RaiteRaju.Web.Models;
using System.IO;
using System.Text.RegularExpressions;
using RaiteRaju.ApplicationUtility;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;

namespace RaiteRaju.Web.Controllers
{
    public class BookController : ErrorController
    {
        public ActionResult GetVehicleTypes()
        {
            InformationServiceWrapper objservice = new InformationServiceWrapper();
            return Json(objservice.GetVehicleTypes(), JsonRequestBehavior.AllowGet);

        }

        public ActionResult BookNow(int vehicleTypeId)
        {
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();
            ViewBag.VehicleTypeId = vehicleTypeId;

            if (UserNameCookie != null && KeyCookie != null)
            {
                ViewBag.Enable = "DISABLE";
            }
            else if (UserNameCookie != null && OTPCookie != null)
            {
                ViewBag.Enable = "DISABLE";
            }
            else
            {
                ViewBag.Enable = "ENABLE";
            }
            return View();
        }

        [HttpPost]
        public ActionResult BookNow(FormCollection form)
        {
            Ride ridesObj = new Ride();
            Utility en = new Utility();
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];

            Random r = new Random();
            Int32 OTP = 0;

            if (PhoneNumberCookie!=null && UserNameCookie != null)
            {
                ridesObj.PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                ridesObj.Name = Convert.ToString(UserNameCookie["_RRUN"]);
            }
            else
            {
                ridesObj.PhoneNumber = Convert.ToInt64(form["txtPhoneNumber"]);
                ridesObj.Name = form["txtUserName"];

                OTP = r.Next(100000, 999999);
                ridesObj.OTP = OTP;
            }
            ridesObj.DropLocation = form["txtDropLocation"];
            ridesObj.PickUpLocation = form["txtPickUpLocation"];
            ridesObj.VehicleTypeID = Convert.ToInt32(form["intVehicleTypeId"]);
            ridesObj.Password = en.Encrypt(ridesObj.PhoneNumber.ToString());
            //ridesObj.RefrerredByPhoneNumber = !string.IsNullOrEmpty(form["txtReferredBy"]) ? Convert.ToInt64(form["txtReferredBy"]) : 0;
            
           
            HttpCookie OTPCookie = new HttpCookie("_ROTP_");
            OTPCookie.Values["_ROTP_"] = en.Encrypt(OTP.ToString());
            OTPCookie.Expires = DateTime.Now.AddMinutes(15);
            Response.Cookies.Add(OTPCookie);

            ManagementServiceWrapper manageObj = new ManagementServiceWrapper();
            int returnValue = manageObj.BookNow(ridesObj);

            return Json(returnValue, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public ActionResult PriceCalculator(FormCollection form)
        {
            int Kilometers = Convert.ToInt32(form["txtKilometers"]);
            int vehicleTypeID = Convert.ToInt32(form["intVehicleTypeId"]);
            string TravelRequestType = Convert.ToString(form["TravelRequestType"]);
            InformationServiceWrapper objservice = new InformationServiceWrapper();
            PriceModel price = objservice.GetPriceForRide(Kilometers, vehicleTypeID, TravelRequestType);
            return Json(price.FinalPrice, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PriceCalculator()
        {
            return View();
        }


        public ActionResult BookNowAPITesting()
        {
            return View();
        }
    }
}
    

RaiteRaju.Web/Controllers/PartnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RaiteRaju.ServiceMapper;
using RaiteRaju.Web.Models;
using System.Web.UI.WebControls;
using System.Text.RegularExpressions;
using RaiteRaju.ApplicationUtility;

namespace RaiteRaju.Web.Controllers
{
    public class PartnerController : ErrorController
    {
        // GET: Partner

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OwnerRegistration()
        {
                return View();
        }

        [HttpPost]
        public ActionResult OwnerRegistration(FormCollection form)
        {
            Owner model = new Owner();
            Utility en = new Utility();

            Random r = new Random();
            Int32 OTP = r.Next(100000, 999999);

            Int32 ownerID = 0;

            model.txtOwnerName = form["txtUserName"];
            model.BigIntPhoneNumber = Convert.ToInt64(form["txtPhoneNumber"]);
            model.txtPassword = en.Encrypt(form["txtPassword"]);
            model.intStateId = Convert.ToInt32(form["ddlStateID"]);
            model.intDistrictId = Convert.ToInt32(form["ddlDistrictID"]);
            model.intManadalID = Convert.ToInt32(form["ddlMandalID"]);
            model.txtPlace = form["txtVillage"];
            model.OTP = OTP;

            string errorMessage = "";

            string s = "[^<>'\"/`%-]";
            if (!System.Text.RegularExpressions.Regex.IsMatch(model.txtOwnerName, s))
            {
                errorMessage = errorMessage + "Special character are not allowed in Name.\n";
            }

            if (!System.Text.RegularExpressions.Regex.IsMatch(en.Decrypt(model.txtPassword), s))
            {
                errorMessage = errorMessage + "Special character are not allowed in password.\n";
            }

            if (!System.Text.RegularExpressions.Regex.Match(model.BigIntPhoneNumber.ToString(), @"^[56789]\d{9}$").Success)
            {
                errorMessage = errorMessage + "Enter valid Phone Number.\n";
            }

            if (!Regex.Match(model.intStateId.ToString(), "[1-9]").Success)
            {
                errorMessage = errorMessage + "Select valid State.\n";
            }

            if (!Regex.Match(model.intDistrictId.ToString(), "[1-9]").Success)
            {
                errorMessage = errorMessage + "Select valid District.\n";
            }

            if (!Regex.Match(model.intManadalID.ToString(), "[1-9]").Success)
            {
                errorMessage = errorMessage + "Select valid Mandal.\n";
            }


            if (!System.Text.RegularExpressions.Regex.IsMatch(model.txtPlace, s))
            {
                errorMessage = errorMessage + "special characters are not allowed in Place.\n";
            }


            GDictionaryModel GDOBJ = new GDictionaryModel();
            if (errorMessage == "")
            {
                ManagementServiceWrapper ObjService = new ManagementServiceWrapper();
                InformationServiceWrapper infoObj = new InformationServiceWrapper();
                GDOBJ = infoObj.MobileNuberExistsOrNot(model.BigIntPhoneNumber, UserType.owner.ToString());
                if (GDOBJ.ID == 1)
                {
                    ManagementServiceWrapper serviceObj = new ManagementServiceWrapper();


                    ownerID = serviceObj.VehicleOwnerRegistration(model);

                    if (ownerID != 0)
                    {
                        HttpCookie KeyCookie = new HttpCookie("_RRPS");
                        KeyCookie.Values["_RRPS"] = en.Encrypt(model.txtPassword);
                        KeyCookie.Expires = DateTime.Now.AddDays(365);
                        Response.Cookies.Add(KeyCookie);
                    }
                    return Json("success", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    errorMessage = "Entered mobiler number is already registered with us.\n";
                    return Json(errorMessage, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(errorMessage, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult _VehicleList(int PageNumber)
        {
            int TotalPageNumber = 0;
            ViewBag.CurrentPageNumber = PageNumber;
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();

            if (UserNameCookie != null && KeyCookie != null)
            {
                Int64 PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                string PassWord = en.Decrypt(KeyCookie["_RRPS"].ToString());
                List<Vehicle> ListObj = new List<Vehicle>();
                InformationServiceWrapper Obj = new InformationServiceWrapper();
                ListObj = Obj.GetVehicleDetails(PhoneNumber, PassWord, PageNumber, out TotalPageNumber);
                if (ListObj != null)
                {
                    ViewBag.vehicleList = ListObj;
                }
            }
            else if (UserNameCookie != null && OTPCookie != null)
            {
                Int64 PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                Utility UtilObj = new Utility();
                string OTP = UtilObj.Decrypt(OTPCookie["_ROTP_"]);
                List<Vehicle> ListObj = new List<Vehicle>();
                InformationServiceWrapper Obj = new InformationServiceWrapper();
                ListObj = Obj.GetVehicleDetails(PhoneNumber, OTP, PageNumber, out TotalPageNumber);
                if (ListObj != null)
                {
                    ViewBag.vehicleList = ListObj;
                }
            }
            ViewBag.TotalPageNumber = TotalPageNumber;
            return PartialView("_VehicleList");
        }

        public ActionResult AddVehicle()
        {

            return View();
        }

        [HttpPost]
        public ActionResult AddVehicle(FormCollection form)
        {
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();
            string returnvalue = "";
            if ((PhoneNumberCookie != null && KeyCookie != null) || (PhoneNumberCookie != null && OTPCookie != null))
            {
                Vehicle model = new Vehicle();
                model.BigIntPhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                model.intVehicleTypeID = Convert.ToInt32(form["ddlVehicleTypeID"]);
                model.txtVehicleName = form["txtVehicleModel"];
                model.txtVehicleNumber = form["txtVehicleNumber"].ToUpper();

                ManagementServiceWrapper mangeObj = new ManagementServiceWrapper();
                returnvalue=mangeObj.AddVehicle(model);
                return Json(returnvalue, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(returnvalue, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult DeleteVehicle(int VehicleID)
        {
            int succuss = 0;
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();
            if (PhoneNumberCookie != null)
            {

                ManagementServiceWrapper obj = new ManagementServiceWrapper();
                Int64 BigIntPhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                obj.DeleteVehicle(VehicleID, BigIntPhoneNumber);
                return Json(1, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Json(succuss, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EditVehicleDetails(int VehicleID)
        {
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];
            HttpCookie OTPCookie = Request.Cookies["_ROTP_"];
            Utility en = new Utility();

            if ((PhoneNumberCookie != null && KeyCookie != null) || (PhoneNumberCookie != null && OTPCookie != null))
            {
                InformationServiceWrapper obj = new InformationServiceWrapper();
                Vehicle model = new Vehicle();
                Int64 PhoneNumber = Convert.ToInt64(en.Decrypt(PhoneNumberCookie["_RRUPn"]));
                model = obj.GetVehicledDetailsByID(VehicleID, PhoneNumber);
                ViewBag.VehicleTypeID = model.intVehicleTypeID;
                ViewBag.VehicleName = model.txtVehicleName;
                ViewBag.VehicleNumber = model.txtVehicleNumber;
                ViewBag.VehicleId = model.intVehicleID;

                    
            }
            return View();
        }

        [HttpPost]
        public ActionResult UpdateVehicleDetails(FormCollection form)
        {
            HttpCookie KeyCookie = Request.Cookies["_RRPS"];
            HttpCookie UserIdCookie = Request.Cookies["_RRUID"];
            HttpCookie UserNameCookie = Request.Cookies["_RRUN"];
            HttpCookie PhoneNumberCookie = Request.Cookies["_RRUPn"];

RaiteRaju.Web/Views/Partner/AddVehicle.cshtml
@{
    ViewBag.Title = "AddVehicle";
    Layout = "~/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.loading-indicator.min.js"></script>
<link type="text/css" rel="stylesheet" href="~/Content/css/jquery.loading-indicator.css" />
<script type="text/javascript">
    $.noConflict();
    jQuery("#diverror").hide();

    function fnCancel() {
        window.location.href = '@Url.Action("Home", "Home")';
    }

    function validation() {

        var vehicleTypeID = jQuery("#ddlVehicles").val();
        var txtVehicleModel = jQuery("#txtVehicleModel").val();
        var txtVehicleNumber = jQuery("#txtVehicleNumber").val().toUpperCase();

        intRegex = /^[5-9]{1}[0-9]{9}$/;
        //vehicleNumberRegex = /^[A - Z]{ 2 } [-][0 - 9]{ 1, 2 } (?: [A - Z]) ? (?: [A - Z] *) ? [0 - 9]{ 4 } $/
        vehicleNumberRegex =/^[A-Z]{2}[0-9]{1,2}[A-Z]{1,2}[0-9]{4}$/;
        var intRegex = /^\d+$/;
        var message = "";



        if (vehicleTypeID == "0" || vehicleTypeID == "---Select Vehicle---") {
            message = message + "Please select Vehicle Type.\n";
        }

        if (txtVehicleModel == "") {
            message = message + "Please enter Vehicle Model.\n";
        }
        else if (txtVehicleModel.length > 50 || txtVehicleModel.length < 4) {
            message = message + "Vehicle Model should be between 4 to 50 characters.\n";
        }
        else if (/^[^<>'\"/`%-]*$/.test(txtVehicleModel) == false) {

            message = message + "Special characters(<>'\"/`%-) are not allowed in Vehicle Model.\n";
        }

        if (txtVehicleNumber == "") {
            message = message + "Please enter Vehicle Number.\n";
        }
        else if (vehicleNumberRegex.test(txtVehicleNumber) == false) {
            message = message + "Please enter valid vehicle number.\n";
        }


        if (message == "") {
            return true;
        }
        else {
            alert(message);
            return false
        }
    }

    function fnRegistration() {
        var form = jQuery("#AddVehicleForm").serialize();
      
        var vehicleTypeID = jQuery("#ddlVehicles").val();
        form += "&ddlVehicleTypeID=" + vehicleTypeID;

        if (validation()) {

            jQuery.ajax({
                type: 'POST',
                url: '@Url.Action("AddVehicle", "Partner")',
                dataType: 'json',
                data: form,
                success: function (data) {
                    if (data == "success") {
                        jQuery('body').loadingIndicator();
                        jQuery("#AddVehicleForm")[0].reset();
                        window.location.href = '@Url.Action("UserAccount", "User")';
                    }
                    else if (data == "exists") {
                        alert("Attached vehicle number already exists with us. Please check vehicle Number.");
                    }
                    else if ("faile") {
                        alert("Error occured, Please try after some time.");

                    }
                },
                error: function (data) {

                    alert("Some Error Occured");
                    jQuery("#diverror").show();
                }
            });
        }
    }
    jQuery(function () {
        jQuery("#ddlState").change(function () {
            var stagId = jQuery("#ddlState").val();

            jQuery('#ddlDistrict').empty();
            jQuery("#ddlDistrict").html("");
            jQuery("#ddlDistrict").append
            (jQuery('<option></option>').val("0").html("---Select District---"));
            if (stagId != "") {
                jQuery.ajax({
                    type: "POST",
                    url: '@Url.Action("FetchDistricts", "Home")',
                    data: '{StateId:"' + stagId + '"}',
                    contentType: "application/json;charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        jQuery.each(result, function (i) {
                            jQuery("#ddlDistrict").append(jQuery('<option></option>').val(result[i].ID).html(result[i].Name))
                        });
                    },
                    error: function (response) {
                        alert('Error Occured');
                    }
                });
            }
            jQuery('#ddlMandal').empty();
            jQuery("#ddlMandal").html("");
            jQuery("#ddlMandal").append
            (jQuery('<option></option>').val("0").html("---Select Mandal---"));
        })
    });

    jQuery(function () {
        jQuery("#ddlDistrict").change(function () {

            var DistID = jQuery("#ddlDistrict").val();
            jQuery('#ddlMandal').empty();
            jQuery("#ddlMandal").html("");
            jQuery("#ddlMandal").append(jQuery('<option></option>').val("0").html("---Select Mandal---"));

            if (DistID != "") {
                jQuery.ajax({
                    type: "POST",
                    url: '@Url.Action("FetchMandals", "Home")',
                    data: '{DistrictId:"' + DistID + '"}',
                    contentType: "application/json;charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        jQuery.each(result, function (i) {
                            jQuery("#ddlMandal").append(jQuery('<option></option>').val(result[i].ID).html(result[i].Name))
                        });
                    },
                    error: function (response) {
                        alert('Error Occured');
                    }
                });
            }
        })
    });

    jQuery(document).ready(function () {
        jQuery.ajax({
            type: "POST",
            url: '@Url.Action("GetVehicleTypes", "Book")',
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                jQuery.each(result, function (i) {
                    jQuery("#ddlVehicles").append(jQuery('<option></option>').val(result[i].ID).html(result[i].Name));
                });
                },
                    error: function (response) {
                        alert('Error Occured');
                    }
        });
    });


</script>
@{Html.EnableClientValidation();}
@{Html.EnableUnobtrusiveJavaScript();}

<div id="divSingUp">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("AttachVehicle", "Partern", FormMethod.Post, new { id = "AddVehicleForm" }))
                {
                    <h3 class="FormHeading">Enter your vehicle details to add with us</h3>
                    <label class="ResponseMessage"></label>
                    <div class="form-box clearfix">
                        <h3 class="form-heading text-center">Add Now</h3>
                        <div class="row">

                       
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 text-center">
                                        <label for="ddlState">Vehicle Type<span class="MandatoryStars">*</span> :</label>
                                    </div>
                                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                                        <select id="ddlVehicles" class="form-control text-right">
                                            <option value="0">---Select Vehicle---</option>
                                        </select>
                                        <span class="error-msg" id="ErrorddlState">Please select required vehicle</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 text-center">
                                        <label for="txtVehicleModel">Vehicle Model<span class="MandatoryStars">*</span> :</label>
                                    </div>
                                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                                        <input type="text" class="form-control" id="txtVehicleModel" name="txtVehicleModel" placeholder=" Ex: Innova">
                                        <span class="error-msg" id="ErrortxtVehicleModel">Please enter a valid vehicle model</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 text-center">
                                        <label for="txtVehicleNumber">Vehicle Number<span class="MandatoryStars">*</span> :</label>
                                    </div>
                                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                                        <input type="text" class="form-control" id="txtVehicleNumber" name="txtVehicleNumber" placeholder=" Ex: AP 00 AB 1234">
                                        <span class="error-msg" id="ErrortxtVehicleNumber">Please enter a valid Vehicle Number</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                                <div class="cta-actions">
                                    <input id="btnRegister" type="button" value="Submit Details" class="ghost-btn first last filled" onclick="fnRegistration()" />
                                </div>
                            </div>

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>